### ISSUE TITLE
[feedback] Support "grid" view in sr_listings short-code

### ISSUE THREAD

**Issue by CodyReichert** [SimplyRETS/simplyretswp#86]
The [sr_listings] short-code right now shows each listing on it's own line. A few people have asked if a "grid view" style layout is available with that short-code -- pretty much exactly how [sr_listings_slider] looks, but with the other short-code.

---

**Example**
```
[sr_listings grid="true"]
```

**Solution**
Basically, just add an additional class -- `.sr-listing-grid-item` -- to each listing if the `grid` prop is set.

Then apply this CSS:
```css
.sr-listing.sr-listing-grid-item {
  display: inline-block !important;
  width: 33%;
}

.sr-listing.sr-listing-grid-item .sr-photo {
  display: inline-block !important;
  width: 100%;
  max-height: 155px;
  background-size: cover;
}

.sr-listing.sr-listing-grid-item .sr-listing-data-wrapper {
  width: 100%;
}

.sr-listing.sr-listing-grid-item + hr { 
  display: none;
}
```

**Comment by CodyReichert** [comment]
In case any clients want to try to apply their own CSS before this is available in the plugin, here are the CSS rules that work for me right now.

**Note: This does not work 100% correctly on all themes, which is why it's not available in the plugin yet. If it doesn't work immediately, try lowering the `width` for `.sr-listing`.**

```css
.sr-listing {
  display: inline-block !important;
  width: 33%;
  vertical-align: text-top;
}

.sr-listing .sr-photo {
  display: inline-block !important;
  width: 100%;
  max-height: 155px;
  background-size: cover;
}

.sr-listing .sr-listing-data-wrapper {
  width: 100%;
}

.sr-listing + hr { 
  display: none;
}
```

Which renders as:

![image](https://user-images.githubusercontent.com/7034627/50652700-f1ca2a00-0f4c-11e9-8c21-98088074a458.png)
